[package]
name = "motorsport_calendar_api"
version = "0.1.0"
authors = ["Michael Ashe <mickjohnashe@hotmail.com>"]

[[bin]]
name = "motorsport_calendar_api"
path = "src/main.rs"

# [[bin]]
# name = "admin_page"
# path = "src/admin_page.rs"

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_yaml = "0.7.3"
serde_json = "1.0.9"
log = "0.4"
env_logger = "0.4"
log4rs = "0.8"
lazy_static = "0.2.2"
clap = "2.29"
diesel = { version = "1.0", features = ["sqlite", "chrono"] }
# diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.10.1"
chrono = "0.4"
tera = "0.10.10" # Just need this for the context struct

[dependencies.motorsport_calendar_common]
path = "/home/mick/Programs/rust/motorsport_calendar_common"

# [dev-dependencies]
# rocket = { version = "0.3.2", features = ["testing"] }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]
