[package]
name = "motorsport_calendar_api"
version = "0.1.0"
authors = ["Michael Ashe <mickjohnashe@hotmail.com>"]

[[bin]]
name = "data_validator"
path = "src/data_validator.rs"

[[bin]]
name = "motorsport_calendar_api"
path = "src/main.rs"

[dependencies]
rocket = "0.2.2"
rocket_codegen = "0.2.2"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
serde_json = "0.9"
log = "0.3"
env_logger = "0.3"
log4rs = "0.6.2"
lazy_static = "0.2.2"

[dependencies.motorsport_calendar_common]
path = "/home/mick/Programs/rust/motorsport_calendar_common"

[dev-dependencies]
rocket = { version = "0.2.2", features = ["testing"] }
