[package]
name = "motorsport_calendar_api"
version = "0.1.0"
authors = ["Michael Ashe <mickjohnashe@hotmail.com>"]

# [[bin]]
# name = "event_manager"
# path = "src/event_manager.rs"

# [[bin]]
# name = "motorsport_calendar_api"
# path = "src/main.rs"

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
serde_json = "1.0.2"
log = "0.3"
env_logger = "0.3"
log4rs = "0.6.2"
lazy_static = "0.2.2"
clap = "2.23.1"
diesel = { version = "0.16.0", features = ["sqlite", "chrono"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.9.0"
chrono = "0.4"
itertools = "0.7.1"


[dependencies.motorsport_calendar_common]
path = "/home/mick/Programs/rust/motorsport_calendar_common"

# [dev-dependencies]
# rocket = { version = "0.3.2", features = ["testing"] }
